const getImagesFromPublic = {
    a: '/img/a.png',
    b: '/img/b.png',
    c: '/img/c.png',
    d: '/img/d.png',
    e: '/img/e.png',
    f: '/img/f.png',
    g: '/img/g.png',
    h: '/img/h.png',
    i: '/img/i.png',
    j: '/img/j.png',
    k: '/img/k.png',
    l: '/img/l.png',
    m: '/img/m.png',
    n: '/img/n.png',
    o: '/img/o.png',
    p: '/img/p.png',
    q: '/img/q.png',
    r: '/img/r.png',
    s: '/img/s.png',
    t: '/img/t.png',
    u: '/img/u.png',
    v: '/img/v.png',
    w: '/img/w.png',
    x: '/img/x.png',
    y: '/img/y.png',
    z: '/img/z.png',
}

export const getPublicImagePath = imageName => getImagesFromPublic[imageName]
